name: rua_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  
  # Google Sign In
  google_sign_in: ^6.1.5
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.2
  blur: ^3.1.0
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  
  # Modern UI Components
  floating_bottom_navigation_bar: ^1.5.2
  curved_navigation_bar: ^1.0.3
  bottom_navy_bar: ^6.0.0
  salomon_bottom_bar: ^3.3.2
  convex_bottom_bar: ^3.2.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  card_swiper: ^3.0.1
  
  # Advanced Animations
  rive: ^0.12.4
  animations: ^2.0.11
  auto_animated: ^3.2.0
  flutter_sequence_animation: ^4.0.0
  morpheus: ^1.1.2
  simple_animations: ^3.1.1
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # Audio Recording
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0
  
  # HTTP
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
 