name: rua_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core - Mevcut uyumlu versiyonlar
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.10.7
  
  # Google Sign In
  google_sign_in: ^6.3.0
  
  # ==================== ABONELIK SISTEMI ====================
  # In-App Purchase (Subscription Management)
  in_app_purchase: ^3.1.13
  
  # Google Mobile Ads (AdMob - Rewarded Ads)
  google_mobile_ads: ^5.1.0
  
  # Yardımcı Paketler
  path_provider: ^2.1.3
  uuid: ^4.4.0
  # =========================================================
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.2
  blur: ^4.0.2
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.3.2
  
  # Modern UI Components
  floating_bottom_navigation_bar: ^1.5.2
  curved_navigation_bar: ^1.0.3
  bottom_navy_bar: ^6.0.0
  salomon_bottom_bar: ^3.3.2
  convex_bottom_bar: ^3.2.0
  flutter_svg: ^2.0.9
  lottie: ^3.1.2
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  card_swiper: ^3.0.1
  
  # Advanced Animations
  rive: ^0.13.13
  animations: ^2.0.11
  auto_animated: ^3.2.0
  flutter_sequence_animation: ^4.0.0
  morpheus: ^1.1.2
  simple_animations: ^5.0.2
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # Audio Recording
  flutter_sound: ^9.2.13
  permission_handler: ^11.4.0
  
  # HTTP
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Assets (Eğer lottie animasyonları vs kullanacaksanız)
  # assets:
  #   - assets/images/
  #   - assets/lottie/