// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDCU3a3jES2BgSEL0dNf8afftOHWkA74',
    appId: '1:237643816620:web:461e059e9b0003f9710909',
    messagingSenderId: '237643816620',
    projectId: 'dreamy-app-2025',
    authDomain: 'dreamy-app-2025.firebaseapp.com',
    storageBucket: 'dreamy-app-2025.firebasestorage.app',
    measurementId: 'G-LY4ND7JDYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN9VTpjsfywnYNlhBYb3B8aAFofi7FYKc',
    appId: '1:237643816620:android:48955560b852b13e710909',
    messagingSenderId: '237643816620',
    projectId: 'dreamy-app-2025',
    storageBucket: 'dreamy-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDcWaKiZGOJwbTTIBfISYg1TGQjSj_q8',
    appId: '1:237643816620:ios:68d5b3d73c4849e4710909',
    messagingSenderId: '237643816620',
    projectId: 'dreamy-app-2025',
    storageBucket: 'dreamy-app-2025.firebasestorage.app',
    iosBundleId: 'com.dreamy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMDcWaKiZGOJwbTTIBfISYg1TGQjSj_q8',
    appId: '1:237643816620:ios:87b1bcaa3571f213710909',
    messagingSenderId: '237643816620',
    projectId: 'dreamy-app-2025',
    storageBucket: 'dreamy-app-2025.firebasestorage.app',
    iosBundleId: 'com.dreamy.app',
  );
}
